# set color
set -g default-terminal "screen-256color"

# set new prefix hotkrys
unbind-key C-b
set -g prefix C-a
bind-key C-a send-prefix

# Enable mouse useage
set -g mouse on

unbind %
bind / split-window -h
